/** @module */

const { mongoose, slugify } = require('../lib/utils')

const marked = require('marked').parse
const createDomPurify = require('dompurify')
const { JSDOM } = require('jsdom')

const dompurify = createDomPurify(new JSDOM().window)

/** @typedef {'blogpost'|'feature'|'faq'|'other'} ArticleKind */
/** @typedef {ArticleKind[]} ArticleKindList */

/** @type {ArticleKindList} */
const ArticleKindList = ['blogpost', 'feature', 'faq', 'other']

/**
 * Description placeholder
 *
 * @typedef {Object} Article
 *
 * @property {String} title
 * @property {String} [description]
 * @property {ArticleKind} kind=blogpost
 * @property {String} date
 * @property {String} markdown
 * @property {String} sanitizedHtml - autogenerated
 * @property {String} slug - autogenerated
 * @property {String} createdBy=unknown
 * @property {String} updatedBy=unknown
 * @property {Date} createdAt - autogenerated
 * @property {Date} updatedAt - autogenerated
 *
 * @example
 * {
 *    "title": "This is an article.",
 *    "description": "This is a description of the article.",
 *    "kind": "blogpost",
 *    "date": "2023-01-01",
 *    "markdown": "# Hello World! \n This is the content of my first blog post.",
 *    "santizedHtml": "<H1>Hello World!</H1><P>This is the content of my first blog post.</P>",
 *    "slug": "this-is-an-article",
 *    "createdBy": "unknown",
 *    "updatedBy": "unknown",
 *    "_id": ObjectId("65086de0d098bb991b21cf49"),
 *    "createdAt": "2023-09-08T18:55:15.430Z"
 *    "updatedAt": "2023-09-08T18:55:15.430Z"
 * }
 */
const ArticleSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true
    },
    description: {
      type: String
    },
    kind: {
      type: String,
      default: 'blogpost',
      required: true,
      enum: ArticleKindList
    },
    date: {
      type: String,
      required: true,
      default: new Date().toISOString().slice(0, 10),
      validate: {
        validator: v => /^\d{4}-\d{2}-\d{2}$/.test(v)
      }
    },
    markdown: {
      type: String,
      required: true
    },
    sanitizedHtml: {
      type: String,
      required: true
    },
    slug: {
      type: String,
      required: true,
      unique: true
    },
    createdBy: {
      type: String,
      default: 'unknown'
    },
    updatedBy: {
      type: String,
      default: 'unknown'
    }
  },
  {
    timestamps: true
  }
)

ArticleSchema.pre('validate', function (next) {
  if (this.title) {
    this.slug = slugify(this.title, { lower: true, strict: true })
  }
  if (this.markdown) {
    this.sanitizedHtml = dompurify.sanitize(
      marked(this.markdown, { mangle: false, headerIds: false })
    )
  }
  next()
})

module.exports = {
  /** @type {MongooseModel} */
  Article: mongoose.model('Article', ArticleSchema),
  /** @type {MongooseSchema} */
  ArticleSchema,
  /** @type {ArticleKindList} */
  ArticleKindList
}
