/* eslint-disable camelcase */
/**
 * @module
 */

const { _, mongoose, slugify } = require('../lib/utils')

const { PhotoSchema } = require('./Photo')

/**
 * List of Photos in an Album
 *
 * @typedef {Array.<PhotoSchema>} ListOfPhotos
 */

/** @type {ListOfPhotos} */
const ListOfPhotos = [PhotoSchema]

const EventSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  date: {
    type: String,
    validate: {
      validator: v => /^\d{4}-\d{2}-\d{2}$/.test(v),
      message: 'must be in the form yyyy-mm-dd'
    },
    required: true
  },
  slug: { // autogenerated
    type: String,
    required: true
  },
  photos: ListOfPhotos,
  createdBy: {
    type: String,
    default: 'unknown'
  },
  updatedBy: {
    type: String,
    default: 'unknown'
  }
}, {
  timestamps: true
})

module.exports = {
  /** @type {MongooseModel} */
  Event: mongoose.model('Event', EventSchema),
  /** @type {MongooseSchema} */
  EventSchema
}